In [19]:
pip install -U fortran-magic

In [20]:
%reload_ext fortranmagic

/usr/local/lib/python3.7/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


In [21]:
%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

The fortranmagic extension is already loaded. To reload it, use:
  %reload_ext fortranmagic


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [22]:
assert ran_the_first_cell, "Oh noes!"

In [23]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

**My own example 1**

In [24]:
example_list = [1,2,3,4,"a","$","j",3.2]
example_list

[1, 2, 3, 4, 'a', '$', 'j', 3.2]

In [25]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


**My own example 2**

In [26]:
first_example = example_list[0]
second_example = example_list[1]
third_example = example_list[2]
print("first of my list: ", first_example)
print("second of my list: ", second_example)
print("third of my list: ", third_example)

first of my list:  1
second of my list:  2
third of my list:  3


In [27]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


**My own example 3**

In [28]:
last_example = example_list[-1]
penultimate_example = example_list[-2]
print("last my example list: ", last_example)
print("second to lasto f my example: ", penultimate_example)

last my example list:  3.2
second to lasto f my example:  j


In [29]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

**My example 4**

In [30]:
sublist_example = example_list[2:4]
sublist_example

[3, 4]

In [31]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

**My example 5**

In [32]:
first_three_ex = example_list[:3]
first_three_ex

[1, 2, 3]

In [33]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

**My own example 6**

In [34]:
after_four_ex = example_list[4:]
after_four_ex

['a', '$', 'j', 3.2]

In [35]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

**My own example 7**

In [36]:
ls_ex = ["a","e", "i","o", "u"]
ls_ex[0::3] 

['a', 'o']

In [37]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

**My own example 8**

In [38]:
ls_ex[::-1]

['u', 'o', 'i', 'e', 'a']

In [39]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


**My own example 9**

In [40]:
ls_ex2 = [10,9,8,7,6,5,4,3,2,1]
print("before :", ls_ex2)
ls_ex2.append("hello")
print("After :",ls_ex2)

before : [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
After : [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 'hello']


In [41]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

**My own example 10**

In [42]:
ls_ex3 = [1,2,3,4,5,6,7,8,9]
[3**x for x in ls_ex3]

[3, 9, 27, 81, 243, 729, 2187, 6561, 19683]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [43]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

**My own example 11**

In [44]:
# Dictionaries are key-value mappings.
movies = {'Harry potter': 'Fantasy', 'Matrix': 'Science fiction', 'The lord of ring': 'Fantasy'}
movies

{'Harry potter': 'Fantasy',
 'Matrix': 'Science fiction',
 'The lord of ring': 'Fantasy'}

In [45]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'Bertrand': 'Russell',
 'David': 'Hume',
 'Immanuel': 'Kant',
 'Ludwig': 'Wittgenstein'}

**My own example 9**

In [46]:
movies["Harry potter"]= "Science fiction"
movies

{'Harry potter': 'Science fiction',
 'Matrix': 'Science fiction',
 'The lord of ring': 'Fantasy'}

In [47]:
del philosophers['David']
philosophers

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

**My own example 10**

In [48]:
del movies["Matrix"]
movies

{'Harry potter': 'Science fiction', 'The lord of ring': 'Fantasy'}

In [49]:
# No slicing.
philosophers['Bertrand':'Immanuel']

TypeError: ignored

**My own example 11**

In [50]:
movies["Harry":"potter"]

TypeError: ignored

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [51]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

**My own example 12**

In [52]:
a_ex = [[3, 5, 7],
     [23, 32, 2],
     [51, 63, 4],
     [12, 13, 15]]

b_ex = [[31, 42, 53, 44],
     [22, 31, 24, 35]]

In [53]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

<center><img src="images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [54]:
%%time

matmul(a, b)

CPU times: user 39 µs, sys: 6 µs, total: 45 µs
Wall time: 51.3 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

In [55]:
%%time

matmul(a_ex, b_ex)

CPU times: user 42 µs, sys: 6 µs, total: 48 µs
Wall time: 53.9 µs


[[203, 281, 279, 307],
 [1417, 1958, 1987, 2132],
 [2967, 4095, 4215, 4449],
 [658, 907, 948, 983]]

In [56]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.28776903185745883, 0.5908196271755628, 0.17416813450157376],
 [0.7615110315677707, 0.6776903474034571, 0.23373736346944163]]

**My own example 13**

In [57]:
randm_ex = random_matrix(4,3)
randm_ex

[[0.7079164107187056, 0.8319413716549608, 0.20677008855965773],
 [0.7614112443781454, 0.6547718479710849, 0.7623737432291475],
 [0.3641170593309956, 0.8409377875421061, 0.6434740056320096],
 [0.2988445056989635, 0.2454593487193184, 0.7335269488489836]]

In [58]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 9.25 s, sys: 26.4 ms, total: 9.28 s
Wall time: 9.3 s


**My own example 14**

In [59]:
%%time
randa_ex = random_matrix(700, 200)
randb_ex = random_matrix(200, 700)
x = matmul(randa_ex, randb_ex)

CPU times: user 26.1 s, sys: 84.8 ms, total: 26.2 s
Wall time: 27.8 s


In [60]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [61]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

In [62]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [63]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 11.6 ms, sys: 0 ns, total: 11.6 ms
Wall time: 12.1 ms


333328333350000.0

In [64]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 153 µs, sys: 5 µs, total: 158 µs
Wall time: 165 µs


333328333350000.0

**My own example 15**

In [65]:
list_data_ex = [float(i) for i in range(300000)]
array_data_ex = np.array(list_data)

In [66]:
%%time
python_dot_product(list_data_ex, list_data_ex)

CPU times: user 29 ms, sys: 0 ns, total: 29 ms
Wall time: 29.1 ms


8999955000050000.0

In [67]:
%%time
fortran_dot_product(array_data_ex, array_data_ex)

CPU times: user 157 µs, sys: 5 µs, total: 162 µs
Wall time: 169 µs


333328333350000.0

<center><img src="images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [68]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

In [69]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [70]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

**My own example 16**

In [71]:
import numpy as np

data_ex = np.array([9,8,7,6,5,4,3,2,1])
data_ex

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [72]:
data + data

array([2, 4, 6, 8])

**My own example 17**



In [73]:
data_ex +data_ex

array([18, 16, 14, 12, 10,  8,  6,  4,  2])

In [74]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 0 ns, sys: 819 µs, total: 819 µs
Wall time: 829 µs


333328333350000.0

**My own example 18**


In [75]:
%%time
# Naive dot product
(array_data_ex * array_data_ex).sum()

CPU times: user 437 µs, sys: 14 µs, total: 451 µs
Wall time: 460 µs


333328333350000.0

In [76]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 327 µs, sys: 11 µs, total: 338 µs
Wall time: 227 µs


333328333350000.0

**My own example 19**



In [77]:
%%time
# Built-in dot product.
array_data_ex.dot(array_data_ex)

CPU times: user 791 µs, sys: 0 ns, total: 791 µs
Wall time: 743 µs


333328333350000.0

In [78]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 158 µs, sys: 0 ns, total: 158 µs
Wall time: 198 µs


333328333350000.0

**My own example 20**


In [79]:
%%time
fortran_dot_product(array_data_ex, array_data_ex)

CPU times: user 147 µs, sys: 5 µs, total: 152 µs
Wall time: 160 µs


333328333350000.0

In [81]:
# Numpy won't allow us to write a string into an int array.
data[0] = "foo"

ValueError: ignored

**My own example 21**



In [82]:
data[2] = "hello world"

ValueError: ignored

In [262]:
# We also can't grow an array once it's created.
data.append(3)

AttributeError: ignored

**My own example 22**


In [264]:
data_ex.append(8)

AttributeError: ignored

In [265]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

ValueError: ignored

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

**My own example 23**


In [267]:
two_by_two_ex = data_ex.reshape(3, 3)
two_by_two_ex

ValueError: ignored

# What's in an Array?

In [268]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [269]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**My own example 24**


In [270]:
data_ex = np.arange(25).reshape(5, 5)
data_ex

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [271]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

**My own example 25**

In [272]:
data_ex *data_ex

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [273]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

**My own example 26**


In [274]:
np.sqrt(data_ex)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

In [275]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

**My own example 27**


In [276]:
data_ex% 2==0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [277]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

**My own example 28**


In [278]:
((data_ex % 2) == 0) & ((data_ex % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [279]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

**My own example 29**


In [280]:
data_ex @ data_ex.T

array([[  30,   80,  130,  180,  230],
       [  80,  255,  430,  605,  780],
       [ 130,  430,  730, 1030, 1330],
       [ 180,  605, 1030, 1455, 1880],
       [ 230,  780, 1330, 1880, 2430]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [281]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

**My own example 30**


In [282]:
sines_ex = np.sin(np.linspace(0, 4.14, 17))
cosines_ex = np.cos(np.linspace(0, 3.14, 17))
sines_ex

array([ 0.        ,  0.25587236,  0.49470904,  0.70060855,  0.85986236,
        0.96186751,  0.99983263,  0.97123004,  0.87796406,  0.72624425,
        0.52617193,  0.29106768,  0.03658449, -0.22033446, -0.4625838 ,
       -0.67403483, -0.8406094 ])

In [283]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

**My own example 31**


In [284]:
sines_ex[0]

0.0

In [285]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

**My own example 32**


In [286]:
sines_ex[:4]

array([0.        , 0.25587236, 0.49470904, 0.70060855])

In [287]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

**My own example 33**


In [288]:
sines_ex[6:] 

array([ 0.99983263,  0.97123004,  0.87796406,  0.72624425,  0.52617193,
        0.29106768,  0.03658449, -0.22033446, -0.4625838 , -0.67403483,
       -0.8406094 ])

In [289]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

**My own example 34**


In [290]:
sines_ex[::2]

array([ 0.        ,  0.49470904,  0.85986236,  0.99983263,  0.87796406,
        0.52617193,  0.03658449, -0.4625838 , -0.8406094 ])

In [291]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


**My own example 35**


In [292]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.2)
print("sines[sines > 0.5]:\n", sines_ex[sines_ex >-0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False  True  True  True  True  True  True  True  True False]
sines[sines > 0.5]:
 [ 0.          0.25587236  0.49470904  0.70060855  0.85986236  0.96186751
  0.99983263  0.97123004  0.87796406  0.72624425  0.52617193  0.29106768
  0.03658449 -0.22033446 -0.4625838 ]


In [293]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

**My own example 36**


In [294]:
print(sines_ex)
sines_ex[[1, 3, 10]]

[ 0.          0.25587236  0.49470904  0.70060855  0.85986236  0.96186751
  0.99983263  0.97123004  0.87796406  0.72624425  0.52617193  0.29106768
  0.03658449 -0.22033446 -0.4625838  -0.67403483 -0.8406094 ]


array([0.25587236, 0.70060855, 0.52617193])

In [295]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

**My own example 37**


In [296]:
unsorted_data_ex = np.array([1,4,5,7,8,4,4,4,5,6,2,2,34,7,5,])

In [297]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

**My own example 38**


In [298]:
sort_indices_ex = np.argsort(unsorted_data_ex)
sort_indices_ex

array([ 0, 10, 11,  1,  5,  6,  7,  2,  8, 14,  9,  3, 13,  4, 12])

In [299]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

**My own example 39**


In [300]:
unsorted_data_ex[sort_indices_ex]

array([ 1,  2,  2,  4,  4,  4,  4,  5,  5,  5,  6,  7,  7,  8, 34])

In [301]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [302]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

**My own example 40**


In [303]:
market_caps_ex = np.array([3, 43, 3, 41, 2, 55, 49])  # Presumably in dollars?
assets_ex = np.array(['A', 'B', 'C', 'D', 'E', "I", "O"])

In [304]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap_ex = np.argsort(market_caps_ex)
assets_ex[sort_by_mcap_ex]

array(['E', 'A', 'C', 'D', 'B', 'O', 'I'], dtype='<U1')

In [305]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [306]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [307]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**My own example 41**


In [308]:
data_ex = np.arange(100).reshape(10, 10)
data_ex

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [309]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

**My own example 42**


In [310]:
data_ex[:3, :2] 

array([[ 0,  1],
       [10, 11],
       [20, 21]])

In [311]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

**My own example 43**


In [312]:
data_ex[:2, [0, -1]] 

array([[ 0,  9],
       [10, 19]])

**My own example 44**


In [313]:
data_ex[:4, [0, -1]] 

array([[ 0,  9],
       [10, 19],
       [20, 29],
       [30, 39]])

In [314]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [315]:
data_ex[(data_ex[:,0]% 5)==0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [316]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [317]:
variance(np.random.standard_normal(1000))

0.9712361770288744

In [318]:
variance(np.random.standard_normal(2000))

1.007098166857146

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [319]:
data = np.arange(30)
data.mean()

14.5

- ...but we can do more interesting things with multi-dimensional arrays.

**My own example 45**


In [320]:
data_ex = np.arange(40)
data_ex.mean()

19.5

In [321]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

**My own example 46**


In [322]:
data_ex = np.arange(40).reshape(10, 4)
data_ex

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [323]:
data.mean()

14.5

**My own example 47**


In [324]:
data_ex.mean()

19.5

In [325]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

**My own example 48**


In [326]:
data_ex.mean(axis=0)

array([18., 19., 20., 21.])

In [327]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

**My own example 49**


In [328]:
data_ex.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5, 25.5, 29.5, 33.5, 37.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [329]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


**My own example 50**


In [330]:
row_ex = np.array([10,9,8,7,6,5])
column_ex = np.array([[1], [2], [3],[4],[5]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [331]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

**My own example 51**


In [332]:
row_ex + column_ex

array([[11, 10,  9,  8,  7,  6],
       [12, 11, 10,  9,  8,  7],
       [13, 12, 11, 10,  9,  8],
       [14, 13, 12, 11, 10,  9],
       [15, 14, 13, 12, 11, 10]])

In [333]:
column = np.array([[1], [2], [3],[4],[5]])


<center><img src="images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [334]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


**My own example 52**





In [335]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data_ex, sep='')
print("Mean:\n", data_ex.mean(axis=0), sep='')
print("Data - Mean:\n", data_ex - data_ex.mean(axis=0), sep='')

Data:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
Mean:
[18. 19. 20. 21.]
Data - Mean:
[[-18. -18. -18. -18.]
 [-14. -14. -14. -14.]
 [-10. -10. -10. -10.]
 [ -6.  -6.  -6.  -6.]
 [ -2.  -2.  -2.  -2.]
 [  2.   2.   2.   2.]
 [  6.   6.   6.   6.]
 [ 10.  10.  10.  10.]
 [ 14.  14.  14.  14.]
 [ 18.  18.  18.  18.]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [336]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

**My own example 53**


In [337]:
s_ex = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[10,9,8,7,6])


In [338]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


**My own example 54**


In [339]:
print("The index is:", s_ex.index)
print("The values are:", s_ex.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [10  9  8  7  6]


In [340]:
# We can look up values out of a Series by position...
s.iloc[0]

1

**My own example 55**


In [341]:
s_ex.iloc[0]

10

In [342]:
# ... or by label.
s.loc['a']

1

**My own example 56**


In [343]:
s_ex.loc["b"]

9

In [344]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

**My own example 57**


In [345]:
s_ex.iloc[:20]

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [346]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

**My own example 58**


In [347]:
s_ex.loc[:'d']

a    10
b     9
c     8
d     7
dtype: int64

In [348]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

**My own example 59**


In [349]:
s_ex.iloc[[0, -2]]

a    10
d     7
dtype: int64

In [350]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

**My own example 60**


In [351]:
s_ex.loc[s_ex < 20]

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [352]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

**My own example 61**


In [353]:
other_s_ex = pd.Series({'a': 33, 'c': 22, 'd': 56, 'z': 33, "y":33})
other_s_ex

a    33
c    22
d    56
z    33
y    33
dtype: int64

In [354]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

**My own example 62**


In [355]:
s_ex + other_s_ex 

a    43.0
b     NaN
c    30.0
d    63.0
e     NaN
y     NaN
z     NaN
dtype: float64

In [356]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

**My own example 63**


In [357]:
(s_ex + other_s_ex).fillna(2.0)

a    43.0
b     2.0
c    30.0
d    63.0
e     2.0
y     2.0
z     2.0
dtype: float64

In [359]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

FileNotFoundError: ignored

**My own example 64**


In [360]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

NameError: ignored

In [361]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

NameError: ignored

# Rolling Operations

<center><img src="images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [362]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

NameError: ignored

In [ ]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

In [ ]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

# "Real World" Data

In [ ]:
from demos.avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

In [ ]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

In [ ]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [ ]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [ ]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

In [ ]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

In [ ]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!